
modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ISenseHostility/forge-improved_berries-1.16.5/issues"

[[mods]] #mandatory
modId="improved_berries" #mandatory
version="forge-1.16.5-1.0.0" #mandatory
displayName="Improved Berries" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/improved_berries"
logoFile="improved_berries.png" #optional
authors="ISenseHostility" #optional
description='''
    Improved Berries adds some new uses for sweet berries.
    '''

[[dependencies.improved_berries]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.improved_berries]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
